[package]
name = "arakodev/mrdialogue"
description = "A dialogue package for Roblox."
version = "0.1.2"
license = "MIT"
authors = ["arakoDev"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/arakoDev/MrDialogue"
include = [
	"default.project.json",
	"src",
	"LICENSE",
	"wally.toml",
]
exclude = [
	"assets",
	"dev.project.json",
	".docs",
	"rokit.toml",
	"selene.toml",
	"sourcemap.json",
	"stylua.toml",
	"README.md",
]

[dependencies]
